wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:8080
  volumes:
    - dev:/var/www/html/wp-content/themes/overnice
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: julian
